classdef TestValidModification < did.unittest.abstract.TestModification
    % TestValidModification
    % Test case for making valid modification to documents

    properties (TestParameter)
        value_modifier = {'sham'},
        id_modifier = {...
            'sham'}
        % 'invalid name' renames an optional dependency (mustbenotempty:0);
        % the declared name is then absent (allowed for optional
        % dependencies) and the renamed entry is an unrecognized dependency,
        % which validation ignores. Hence it is a valid modification.
        dependency_modifier = {...
            'add dependency', ...
            'invalid name'}
        other_modifier = {...
            'invalid definition', ...
            'invalid property list name', ...
            'new class version number', ...
            'class version string', ....
            'invalid base name'}
        % item1/item2/item3 each remove one optional dependency
        % (mustbenotempty:0) from a demoC document. Missing optional
        % dependencies are allowed, so removing them is a valid modification.
        remover = {...
            'definition', ...
            'validation', ...
            'item1', ...
            'item2', ...
            'item3'}
    end

    methods
        function doVerification(testCase, b)
            testCase.verifyFalse(b)
        end
    end
end
