function tests = testMigrators
%TESTMIGRATORS Per-class did_v1 -> V_delta migrator tests.
%
%   Exercises the four 2.0.0-bumped class migrators (PLAN.md §9.6
%   sub-step 6c) against the worked examples in
%   did-schema/schemas/V_delta/conversions/from_did_v1/<class>.md.
%
%   Tests run with Validate=false on the end-to-end dispatcher case
%   so they do not depend on the schema cache being able to resolve
%   V_delta schemas at the test-runner working directory.
%
%   Run with:
%       results = runtests('did2.unittest.testMigrators');

tests = functiontests(localfunctions);
end

function v1 = wrap(className, blockKey, block)
v1 = struct();
v1.document_class = struct( ...
    'class_name',    className, ...
    'class_version', '1.0.0', ...
    'superclasses',  struct( ...
        'class_name',    'base', ...
        'class_version', '1.0.0'));
v1.depends_on = struct('name', {}, 'value', {});
v1.base = struct( ...
    'id',         'aabb1122ccdd3344_1122334455667788', ...
    'session_id', 'aabb1122ccdd3344_9900aabbccddeeff', ...
    'name',       'migrator-example', ...
    'datestamp',  '2024-06-01T12:00:00.000Z');
v1.(blockKey) = block;
end

function testProbeLocationCollapsesTwoChars(testCase)
v1 = wrap('probe_location', 'probe_location', struct( ...
    'ontology_name', 'uberon:0002436', ...
    'name',          'primary visual cortex'));
out = did2.convert.migrators.probe_location( ...
    did2.convert.universalRenames(v1));
verifyEqual(testCase, out.probe_location.location.node, 'uberon:0002436');
verifyEqual(testCase, out.probe_location.location.name, 'primary visual cortex');
verifyFalse(testCase, isfield(out.probe_location, 'ontology_name'));
verifyFalse(testCase, isfield(out.probe_location, 'name'));
end

function testTreatmentMigrationFromCamelCase(testCase)
v1 = wrap('treatment', 'treatment', struct( ...
    'ontologyName',  'chebi:6015', ...
    'name',          'isoflurane', ...
    'numeric_value', 2.0, ...
    'string_value',  '2 percent in O2'));
out = did2.convert.migrators.treatment( ...
    did2.convert.universalRenames(v1));
verifyEqual(testCase, out.treatment.treatment_name.node, 'chebi:6015');
verifyEqual(testCase, out.treatment.treatment_name.name, 'isoflurane');
verifyEqual(testCase, out.treatment.numeric_value, 2.0);
verifyEqual(testCase, out.treatment.string_value, '2 percent in O2');
end

function testTreatmentMigrationFromSnakeCase(testCase)
v1 = wrap('treatment', 'treatment', struct( ...
    'ontology_name', 'chebi:6015', ...
    'name',          'isoflurane', ...
    'numeric_value', 2.0, ...
    'string_value',  '2 percent in O2'));
out = did2.convert.migrators.treatment( ...
    did2.convert.universalRenames(v1));
verifyEqual(testCase, out.treatment.treatment_name.node, 'chebi:6015');
verifyEqual(testCase, out.treatment.treatment_name.name, 'isoflurane');
end

function testOntologyImageRenamesClassAndCollapsesFields(testCase)
v1 = wrap('ontologyImage', 'ontologyImage', struct( ...
    'ontology_name',   'allen_ccf_v3:12345', ...
    'ontology_region', 'primary visual cortex'));
postUniversal = did2.convert.universalRenames(v1);
verifyEqual(testCase, postUniversal.document_class.class_name, 'ontology_image');
out = did2.convert.migrators.ontology_image(postUniversal);
verifyEqual(testCase, out.ontology_image.region.node, 'allen_ccf_v3:12345');
verifyEqual(testCase, out.ontology_image.region.name, 'primary visual cortex');
verifyFalse(testCase, isfield(out, 'ontologyImage'));
end

function testOntologyLabelComposesCURIE(testCase)
v1 = wrap('ontologyLabel', 'ontologyLabel', struct( ...
    'ontology_name', 'Allen CCF v3', ...
    'label',         'primary visual cortex', ...
    'label_id',      12345));
out = did2.convert.migrators.ontology_label( ...
    did2.convert.universalRenames(v1));
verifyEqual(testCase, out.document_class.class_name, 'ontology_label');
verifyEqual(testCase, out.ontology_label.term.node, 'allen_ccf_v3:12345');
verifyEqual(testCase, out.ontology_label.term.name, 'primary visual cortex');
end

function testOntologyLabelHandlesStringLabelId(testCase)
v1 = wrap('ontologyLabel', 'ontologyLabel', struct( ...
    'ontology_name', 'allen_ccf_v3', ...
    'label',         'primary visual cortex', ...
    'label_id',      '12345'));
out = did2.convert.migrators.ontology_label( ...
    did2.convert.universalRenames(v1));
verifyEqual(testCase, out.ontology_label.term.node, 'allen_ccf_v3:12345');
end

function testProbeLocationMissingBlockErrors(testCase)
v1 = struct( ...
    'document_class', struct('class_name', 'probe_location'), ...
    'base',           struct());
verifyError(testCase, @() did2.convert.migrators.probe_location(v1), ...
    'did2:convert:missingBlock');
end

function testEndToEndDispatcherForProbeLocation(testCase)
v1 = wrap('probe_location', 'probe_location', struct( ...
    'ontology_name', 'uberon:0002436', ...
    'name',          'primary visual cortex'));
result = did2.convert.v1_to_v2(v1, 'Validate', false);
verifyEqual(testCase, result.summary.migrated_count, 1);
doc = result.migrated{1};
verifyEqual(testCase, doc.get('probe_location.location.node'), ...
    'uberon:0002436');
verifyEqual(testCase, doc.get('probe_location.location.name'), ...
    'primary visual cortex');
verifyEqual(testCase, doc.get('base.schema_version'), 'V_delta');
end

function testEndToEndDispatcherForOntologyLabel(testCase)
v1 = wrap('ontologyLabel', 'ontologyLabel', struct( ...
    'ontology_name', 'Allen CCF v3', ...
    'label',         'primary visual cortex', ...
    'label_id',      12345));
result = did2.convert.v1_to_v2(v1, 'Validate', false);
verifyEqual(testCase, result.summary.migrated_count, 1);
verifyEqual(testCase, result.summary.by_class.ontology_label, 1);
doc = result.migrated{1};
verifyEqual(testCase, doc.className(), 'ontology_label');
verifyEqual(testCase, doc.get('ontology_label.term.node'), ...
    'allen_ccf_v3:12345');
end
