function testToolbox(varargin)
    projectRootDirectory = didtools.projectdir();
    matbox.installRequirements(projectRootDirectory)
    matbox.tasks.testToolbox(projectRootDirectory, ...
        varargin{:}, ...
        "SourceFolderName", 'src', ...
        "TestsFolderName", 'tests', ...
        "CreateBadge", false ...
        )
end
