function testToolbox(varargin)
    projectRootDirectory = didtools.projectdir();
    matbox.installRequirements(projectRootDirectory)
    matbox.tasks.testToolbox(projectRootDirectory, ...
        "SourceFolderName", 'src', ...
        "TestsFolderName", 'tests', ...
        varargin{:})
end
