classdef buildDatabase < matlab.unittest.TestCase
    % BUILDDATABASE - Read and validate DID database artifacts for cross-language symmetry testing
    %
    % This test reads database artifacts generated by either the MATLAB or Python
    % DID test suite, re-summarizes the database using did.util.databaseSummary,
    % and compares the result against the saved summary using did.util.compareDatabaseSummary.

    properties (TestParameter)
        % Define the two potential sources of artifacts
        SourceType = {'matlabArtifacts', 'pythonArtifacts'};
    end

    methods (Test)
        function testBuildDatabaseArtifacts(testCase, SourceType)
            % Determine the artifact directory expected from either MATLAB or Python
            artifactDir = fullfile(tempdir(), 'DID', 'symmetryTest', SourceType, ...
                'database', 'buildDatabase', 'testBuildDatabaseArtifacts');

            % If the directory does not exist, skip this parameterized test
            testCase.assumeTrue(isfolder(artifactDir), ...
                ['Artifact directory from ' SourceType ' does not exist.']);

            % Step 1: Load the saved summary
            summaryFile = fullfile(artifactDir, 'summary.json');
            testCase.assumeTrue(isfile(summaryFile), ...
                ['summary.json not found in ' SourceType ' artifact directory.']);

            fid = fopen(summaryFile, 'r');
            rawJson = fread(fid, inf, '*char')';
            fclose(fid);
            savedSummary = jsondecode(rawJson);

            testCase.verifyTrue(isfield(savedSummary, 'branchNames'), ...
                'summary.json missing branchNames field.');
            testCase.verifyTrue(isfield(savedSummary, 'dbFilename'), ...
                'summary.json missing dbFilename field.');

            % Step 2: Open the DID database and produce a live summary
            dbPath = fullfile(artifactDir, savedSummary.dbFilename);
            testCase.assumeTrue(isfile(dbPath), ...
                ['Database file not found: ' dbPath]);

            db = did.implementations.sqlitedb(dbPath);
            liveSummary = did.util.databaseSummary(db);

            % Step 3: Compare the saved summary against the live database summary
            report = did.util.compareDatabaseSummary(savedSummary, liveSummary);

            testCase.verifyEmpty(report, ...
                ['Database summary mismatch for ' SourceType ': ' ...
                strjoin(report, '; ')]);

            % Step 4: Also verify per-branch JSON files match the live database
            branchNames = savedSummary.branchNames;
            if ischar(branchNames)
                branchNames = {branchNames};
            end

            jsonBranchesDir = fullfile(artifactDir, 'jsonBranches');
            testCase.assumeTrue(isfolder(jsonBranchesDir), ...
                ['jsonBranches directory not found in ' SourceType]);

            for i = 1:numel(branchNames)
                branchName = branchNames{i};
                safeName = matlab.lang.makeValidName(branchName);

                branchJsonFile = fullfile(jsonBranchesDir, ['branch_' branchName '.json']);
                testCase.assumeTrue(isfile(branchJsonFile), ...
                    ['Branch JSON file missing for ' branchName ' in ' SourceType]);

                fid = fopen(branchJsonFile, 'r');
                rawBranchJson = fread(fid, inf, '*char')';
                fclose(fid);
                savedBranch = jsondecode(rawBranchJson);

                % Verify document count matches the live database
                db.set_branch(branchName);
                actualDocIds = db.get_doc_ids(branchName);
                testCase.verifyEqual(numel(actualDocIds), savedBranch.docCount, ...
                    ['Document count mismatch in branch ' branchName ' from ' SourceType]);

                % Verify each saved document can be found in the live database
                savedDocs = savedBranch.documents;
                if isstruct(savedDocs) && isscalar(savedDocs)
                    savedDocs = {savedDocs};
                end
                if isstruct(savedDocs) && ~isscalar(savedDocs)
                    % struct array from jsondecode — convert to cell
                    tmp = cell(1, numel(savedDocs));
                    for k = 1:numel(savedDocs)
                        tmp{k} = savedDocs(k);
                    end
                    savedDocs = tmp;
                end

                liveDocs = {};
                for j = 1:numel(savedDocs)
                    if iscell(savedDocs)
                        savedDoc = savedDocs{j};
                    else
                        savedDoc = savedDocs(j);
                    end

                    expectedId = savedDoc.id;
                    doc = db.get_docs(expectedId);
                    testCase.verifyNotEmpty(doc, ...
                        ['Document ' expectedId ' from ' SourceType ...
                        ' not found in database branch ' branchName]);

                    if ~isempty(doc)
                        if iscell(doc), doc = doc{1}; end
                        liveDocs{end+1} = doc; %#ok<AGROW>
                        actualProps = doc.document_properties;
                        testCase.verifyEqual(actualProps.document_class.class_name, ...
                            savedDoc.className, ...
                            ['Class name mismatch for doc ' expectedId ...
                            ' in branch ' branchName ' from ' SourceType]);
                    end
                end

                % Step 5: run OUR schema validator over documents the other
                % language wrote.
                %
                % Without this the suite only ever proved each language can
                % READ the other's database. Validation lives in add_docs, and
                % each language calls add_docs only on documents it created
                % itself during makeArtifacts -- so a document one language
                % writes could be schema-invalid under the other's validator
                % with the suite staying green. That is not hypothetical:
                % every Python document id was once a UUID4 where
                % base.schema.json types base.id as did_uid, so this repo's
                % add_docs would have rejected all of them, and the suite
                % noticed nothing until someone read the code. See
                % DID-matlab#155 / DID-python#28.
                if ~isempty(liveDocs)
                    try
                        db.validate_docs(liveDocs);
                    catch validationError
                        testCase.verifyFail(sprintf([ ...
                            'Documents written by %s do not pass this ' ...
                            'language''s schema validator, in branch %s: ' ...
                            '[%s] %s'], SourceType, branchName, ...
                            validationError.identifier, validationError.message));
                    end
                end
            end
        end
    end
end
