classdef buildDatabase < matlab.unittest.TestCase
    % BUILDDATABASE - Read and validate DID database artifacts for cross-language symmetry testing
    %
    % This test reads database artifacts generated by either the MATLAB or Python
    % DID test suite and validates that the documents can be correctly loaded and
    % that their contents match the JSON audit files.

    properties (TestParameter)
        % Define the two potential sources of artifacts
        SourceType = {'matlabArtifacts', 'pythonArtifacts'};
    end

    methods (Test)
        function testBuildDatabaseArtifacts(testCase, SourceType)
            % Determine the artifact directory expected from either MATLAB or Python
            artifactDir = fullfile(tempdir(), 'DID', 'symmetryTest', SourceType, ...
                'database', 'buildDatabase', 'testBuildDatabaseArtifacts');

            % If the directory does not exist, skip this parameterized test
            testCase.assumeTrue(isfolder(artifactDir), ...
                ['Artifact directory from ' SourceType ' does not exist.']);

            % Step 1: Load and validate metadata.json
            metadataFile = fullfile(artifactDir, 'metadata.json');
            testCase.assumeTrue(isfile(metadataFile), ...
                ['metadata.json not found in ' SourceType ' artifact directory.']);

            fid = fopen(metadataFile, 'r');
            rawJson = fread(fid, inf, '*char')';
            fclose(fid);
            metadata = jsondecode(rawJson);

            testCase.verifyTrue(isfield(metadata, 'branchNames'), ...
                'metadata.json missing branchNames field.');
            testCase.verifyTrue(isfield(metadata, 'dbFilename'), ...
                'metadata.json missing dbFilename field.');

            % Step 2: Open the DID database
            dbPath = fullfile(artifactDir, metadata.dbFilename);
            testCase.assumeTrue(isfile(dbPath), ...
                ['Database file not found: ' dbPath]);

            db = did.implementations.sqlitedb(dbPath);

            % Step 3: Validate each branch against its JSON audit file
            branchNames = metadata.branchNames;
            if ischar(branchNames)
                branchNames = {branchNames};
            end

            jsonBranchesDir = fullfile(artifactDir, 'jsonBranches');
            testCase.assumeTrue(isfolder(jsonBranchesDir), ...
                ['jsonBranches directory not found in ' SourceType]);

            for i = 1:numel(branchNames)
                branchName = branchNames{i};

                % Load the expected branch JSON
                branchJsonFile = fullfile(jsonBranchesDir, ['branch_' branchName '.json']);
                testCase.assumeTrue(isfile(branchJsonFile), ...
                    ['Branch JSON file missing for ' branchName ' in ' SourceType]);

                fid = fopen(branchJsonFile, 'r');
                rawBranchJson = fread(fid, inf, '*char')';
                fclose(fid);
                expectedDocs = jsondecode(rawBranchJson);

                % Handle single-doc case where jsondecode returns a struct not array
                if isstruct(expectedDocs) && ~isscalar(expectedDocs)
                    % Already a struct array, leave as-is
                elseif isstruct(expectedDocs) && isscalar(expectedDocs)
                    expectedDocs = {expectedDocs};
                elseif iscell(expectedDocs)
                    % Cell array from jsondecode, leave as-is
                end

                % Get actual documents from the database branch
                db.set_branch(branchName);
                actualDocIds = db.get_doc_ids(branchName);

                % Verify document count matches
                if iscell(expectedDocs)
                    expectedCount = numel(expectedDocs);
                else
                    expectedCount = numel(expectedDocs);
                end
                testCase.verifyEqual(numel(actualDocIds), expectedCount, ...
                    ['Document count mismatch in branch ' branchName ' from ' SourceType ...
                    '. Expected ' num2str(expectedCount) ' but got ' num2str(numel(actualDocIds))]);

                % Verify each expected document exists in the database
                for j = 1:expectedCount
                    if iscell(expectedDocs)
                        expectedDoc = expectedDocs{j};
                    else
                        expectedDoc = expectedDocs(j);
                    end

                    expectedId = expectedDoc.base.id;

                    % Try to retrieve the document from the database
                    doc = db.get_docs(expectedId);
                    testCase.verifyNotEmpty(doc, ...
                        ['Document ' expectedId ' from ' SourceType ' not found in database branch ' branchName]);

                    if ~isempty(doc)
                        actualProps = doc.document_properties;

                        % Verify document class name matches
                        testCase.verifyEqual(actualProps.document_class.class_name, ...
                            expectedDoc.document_class.class_name, ...
                            ['Class name mismatch for doc ' expectedId ' in branch ' branchName ' from ' SourceType]);

                        % Verify demo-type-specific value fields
                        demoFields = {'demoA', 'demoB', 'demoC'};
                        for k = 1:numel(demoFields)
                            fieldName = demoFields{k};
                            if isfield(expectedDoc, fieldName)
                                testCase.verifyTrue(isfield(actualProps, fieldName), ...
                                    ['Missing field ' fieldName ' in doc ' expectedId ' from ' SourceType]);
                                if isfield(actualProps, fieldName)
                                    testCase.verifyEqual(actualProps.(fieldName).value, ...
                                        expectedDoc.(fieldName).value, ...
                                        ['Value mismatch in ' fieldName ' for doc ' expectedId ' from ' SourceType]);
                                end
                            end
                        end

                        % Verify depends_on if present
                        if isfield(expectedDoc, 'depends_on')
                            testCase.verifyTrue(isfield(actualProps, 'depends_on'), ...
                                ['Missing depends_on in doc ' expectedId ' from ' SourceType]);
                        end
                    end
                end
            end

            % Step 4: Verify branch document counts match metadata
            if isfield(metadata, 'branchDocCounts')
                for i = 1:numel(branchNames)
                    branchName = branchNames{i};
                    if isfield(metadata.branchDocCounts, branchName)
                        expectedCount = metadata.branchDocCounts.(branchName);
                        db.set_branch(branchName);
                        actualDocIds = db.get_doc_ids(branchName);
                        testCase.verifyEqual(numel(actualDocIds), expectedCount, ...
                            ['Metadata doc count mismatch for branch ' branchName ' from ' SourceType]);
                    end
                end
            end
        end
    end
end
