name: Prepare toolbox release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in major.minor.patch format'
        required: true
        type: string

jobs:
  reuse-workflow-release:
    name: Prepare toolbox release
    uses: ehennestad/matbox/.github/workflows/reusable_release_workflow.yml@make-release-workflow-reusable
    with:
      # Do not change
      version: ${{ inputs.version }}
      
      # Do not change
      ref_name: ${{ github.ref_name }}
      
      # Path to directory containing source code. This directory will be packaged
      # into the toolbox. Important: This should not be a namespace directory
      code_directory: code
      
      # Path to directory containing tools and MLToolboxInfo.json. Used for finding
      # unit tests, running customized MatBox tasks, and determining toolbox metadata
      tools_directory: tools

      matlab_products: Statistics_and_Machine_Learning_Toolbox
      
    secrets:
      # SSH deploy key for pushing to protected branches. Required for creating
      # releases and updating badges. Generate an SSH key pair and add the public
      # key as a deploy key with write access, then add the private key as this secret
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
