name: Run Codespell

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse-workflow-run-codespell:
    name: Run Codespell
    uses: ehennestad/matbox/.github/workflows/reusable_run_codespell.yml@v0.9
    with:
      config_file: tools/.codespellrc
