name: Run Codespell

on:
  push:
    branches: [ "main", "V2" ]

  pull_request:
    branches: [ "main", "V2" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Run Codespell action
        uses: codespell-project/actions-codespell@v2
