name: Run tests

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'

  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable-test-toolbox-workflow:
    name: Test and analyse code
    uses: ehennestad/matbox/.github/workflows/reusable_test_workflow.yml@add-reusable-test-workflow
    with:
      matlab_release: R2021b
      matlab_use_cache: true
      matlab_products: Statistics_and_Machine_Learning_Toolbox
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
